debug: true
timeZone: "Europe/Warsaw"
server:
  hostname: "127.0.0.1"
  port: 25565
  ops: [ "radek203" ]
checks:
  badVersion: "&cYou are using the wrong version of Minecraft! Switch to: 1.8.x, 1.9.x, 1.10.x, 1.11.x or 1.12.2"
  blockedNames: [ "proxy", "mcstorm", "mcdrop", "mcdown", "null", "spam" ]
  badNameLength: "&cNickname must be between 3 and 16 characters!"
  badNameChars: "&cYour nickname contains forbidden characters &8>> &7"
  badName: "&cYou cannot join using such a nickname!"
motd:
  version: "KMLightSpigot"
  description: "&eThe server is running the KMLightSpigot engine!\nCreated by: radek203"
command:
  notExists: "&cSuch a command does not exist!"
  noPermission: "&cYou do not have access to this command!"
network:
  proxy:
    enabled: false
    ips: [ "127.0.0.1", "localhost" ]
  packets:
    count: 250
    time: 250
  playerOnServer: "&cA player with your nickname is already on the server!"
  restart: "&cServer restart! Please join again in a moment!"
  defaultGamemode: 3
  defaultDimension: 1
  keepAliveBroadcast: 5000
  maxPlayers: -1
  networkThreshold: -1
  chat:
    status: false
    message: "&cYou cannot do this here!"